export const timings = {
    'Jafari / Shia Ithna-Ashari': {
      Fajr: '1',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'University of Islamic Sciences, Karachi': {
      Fajr: '2',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Islamic Society of North America (ISNA)': {
      Fajr: '3',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Muslim World League': {
      Fajr: '0',
      Sunrise: '0',
      Dhuhr: '2',
      Asr: '0',
      Maghrib: '4',
      Isha: '0',
    },
    'Umm Al-Qura University, Makkah': {
      Fajr: '5',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Egyptian General Authority of Survey': {
      Fajr: '6',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Institute of Geophysics, University of Tehran': {
      Fajr: '7',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Gulf Region': {
      Fajr: '8',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Kuwait': {
      Fajr: '9',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Qatar': {
      Fajr: '10',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Majlis Ugama Islam Singapura, Singapore': {
      Fajr: '11',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Union Organization islamic de France': {
      Fajr: '12',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Diyanet İşleri Başkanlığı, Turkey': {
      Fajr: '13',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Spiritual Administration of Muslims of Russia': {
      Fajr: '14',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Moonsighting Committee Worldwide (requires shafaq)': {
      Fajr: '0',
      Sunrise: '0',
      Dhuhr: '5',
      Asr: '0',
      Maghrib: '3',
      Isha: '0',
    },
    'Dubai (experimental)': {
      Fajr: '16',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Jabatan Kemajuan Islam Malaysia (JAKIM)': {
      Fajr: '17',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Tunisia': {
      Fajr: '0',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Algeria': {
      Fajr: '18',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'KEMENAG - Kementerian Agama Republik Indonesia': {
      Fajr: '19',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Morocco': {
      Fajr: '20',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Comunidade Islamica de Lisboa': {
      Fajr: '21',
      Sunrise: '22',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    },
    'Ministry of Awqaf, Islamic Affairs and Holy Places, Jordan': {
      Fajr: '22',
      Sunrise: '0',
      Dhuhr: '0',
      Asr: '0',
      Maghrib: '0',
      Isha: '0',
    }
  };
  